# Generated by Django 6.0.4 on 2026-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingresult',
            name='output_path',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='input_file_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='output_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
